spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emsdb?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port : 8080

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8091/oauth/check_token
    client:
      client-id: web
      client-secret: web